Q1.explain the purpose and advantages of numpy in scientific computing and data analysis. how does it enhance pythons's capabilities for numerical operations?

ans
i) purpose of numpy in pyhton:

numpy, or "numeric python", is a python library tht's used for scientific and mathematical calculations, and is especially useful for data science projects. it has many features and tools that help with 1)data cleaning , transformation, and aggregation.2) mathematical operations3)multi-dimensional arrays4)random number generators5)structuring data



ii)advantage of numpy:

ans:- 1) NUMPY  is faster than python lists, especially when working with large matrices or data sets.2)numpy uses less memory and storage space than python lists.3)numpy can simplify operations between arrays of different sizes.4)numpy can simplify operations on entire arrays without loops, which can improve code clarity and execution speed.5)numpy has a large collection of efficient mathematical functions, including matrix multiplication,eigenvalue calculation,and differential equations.6)numpy has functions for constructiong resizing concatenating, and padding arrays.


Q2.compare and contrast np.mean() and np.average () function in numpy. when would you use one over the other?

ans :

in the numpy library, there are two functions np.mean() and np.average().both are actually doing nealry the same job of calculating mean/average . the difference comes when we are calculating the  weighted average.

np.mean()

1) use to calculate arithmetic mean
2) ALL elements have equal weight
3)weight cannot be passed trough the parameter of the given function.
4)syntax: np.mean(arr,axis=none)

np.average()

1) use to calculate the arithmetic mean as well as weighted average.
2) all elements may or may not have equal weight.
3) weight can be passed through the parameter of the given function.
4) syntax: numpy.average(arr.axis=none,weights=none)





Q3.describe the methods for reversing a numpy array along different axes. provide examples for 1d and 2d arrays.

ans :
using numpy.flip() function reverses the order of array elements along the specifed axis, presrving the shape of the array.

In [ ]:
import numpy as np

arr_1d = np.array([1,2,3,4,5,6,7,8,9])
print(arr_1d)
reversed_arr_1d = np.flip(arr_1d)
print(reversed_arr_1d)

arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr_2d)
arr_2d_rows = np.flip(arr_2d,axis=0)
print(arr_2d_rows)
arr_2d_cols = np.flip(arr_2d,axis=1)
print(arr_2d_cols)


[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


Q4. how can you determine the data type of elements in a numpy array? discuss the importance of data types in memory management and performance.

 ans :

 we can check the type of data present in the numpy array using the "dtype" attribute the data type of array "arr" is "int" (integer). here "32 is related to memory allocation



In [ ]:


import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)


int64


Q5. define ndarry in numpy and explain their key features. how do they differ from standard python lists?

python list :

1)dynamic typing 2)size flexibility 3) versatility 4) slower performance 5) less mathematical functionality

VS

numpy array:

1) homogeneous data types 2) fixed size
3) optimized operations4)better performance 5) memory efficiency 5)broadcasting






In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


Q6.analyze the performance benefits of numpy arrays over python list for large-scale numerical operations.


In [ ]:
import numpy as np
import time
size = 1000000
my_list = list(range(size))
my_array = np.array(range(size))
start_time = time.time()
new_list = [x + 1 for x in my_list]
list_time = time.time() - start_time
start_time = time.time()
new_array = my_array + 1
array_time = time.time() - start_time
print("Time taken for list addition:", list_time)
print("Time taken for numpy array addition:", array_time)
print("Numpy array is", round(list_time / array_time), "times faster than list for element-wise addition.")


Time taken for list addition: 0.07203340530395508
Time taken for numpy array addition: 0.0046045780181884766
Numpy array is 16 times faster than list for element-wise addition.


Q7. compare vstack() and hstack() function in numpy. provide example demonstrating usage and output.


In [ ]:


import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

vertical_stack = np.vstack((arr1, arr2))
print("Vertical Stack:\n", vertical_stack)

horizontal_stack = np.hstack((arr1, arr2))
print("\nHorizontal Stack:\n", horizontal_stack)


arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])
vertical_stack_2d = np.vstack((arr3, arr4))
print("\nVertical Stack 2D:\n", vertical_stack_2d)
horizontal_stack_2d = np.hstack((arr3, arr4))
print("\nHorizontal Stack 2D:\n", horizontal_stack_2d)


Vertical Stack:
 [[1 2 3]
 [4 5 6]]

Horizontal Stack:
 [1 2 3 4 5 6]

Vertical Stack 2D:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack 2D:
 [[1 2 5 6]
 [3 4 7 8]]


Q8. explain the defference between fliplr() and flipud() methods in numpy,including their effects on various array dimensions.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
flipped_lr = np.fliplr(arr)
print("Original array:\n", arr)
print("\nFlipped left-right:\n", flipped_lr)
flipped_ud = np.flipud(arr)
print("\nFlipped up-down:\n", flipped_ud)



arr_1d = np.array([1, 2, 3, 4, 5])
flipped_lr_1d = np.fliplr(arr_1d.reshape(1, -1))
flipped_ud_1d = np.flipud(arr_1d.reshape(1, -1))
print("\nOriginal 1D array:", arr_1d)
print("Flipped left-right (1D):", flipped_lr_1d.flatten())
print("Flipped up-down (1D):", flipped_ud_1d.flatten())


arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
flipped_lr_3d = np.fliplr(arr_3d)
flipped_ud_3d = np.flipud(arr_3d)
print("\nOriginal 3D array:\n", arr_3d)
print("\nFlipped left-right (3D):\n", flipped_lr_3d)
print("\nFlipped up-down (3D):\n", flipped_ud_3d)



Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped left-right:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]

Flipped up-down:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]

Original 1D array: [1 2 3 4 5]
Flipped left-right (1D): [5 4 3 2 1]
Flipped up-down (1D): [1 2 3 4 5]

Original 3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Flipped left-right (3D):
 [[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]

Flipped up-down (3D):
 [[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


Q9.discuss the functionality of  the array_split() method in numpy. how does it handle uneven splits?
ans:

splitting is reverse operation of joining.joining merges multiple arrays into one and splitting breaks one array into multiple.
we use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

numpy.array_split() spliting into equal or nearly equal sub-arrays or is similar  to numpy.split() but it allows for uneven splitting of arrays. this is useful when the array cannot be evenly divided by the specified number of splits. numpy.array_split(array,4)splits the array into four parts accommodating uneven division.


In [ ]:
import numpy as np
arrr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arrr,3)
print(newarr)


array = np.arange(13)
result = np.array_split(array,4)
print("Array:")
print(array)
print("\nResult:")
print("\nResult after numpy.array_split():")
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]
Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]

Result:

Result after numpy.array_split():
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


10. explain the concepts of vectorization and broadcasting in numpy. how do they contribute to efficient array operation?

ans:

1) What is vectorization in numpy:
numpy arrays are homogenous in nature means it is an array that contains data of a single type only. python's  lists and tuples are unrestricted in the type of data they contain. the concept of vectorized operations on numpy allows the use of more optimal and pre-conpiled functions and mathematical operations on numpy array objects and data sequences. the output and operaitons will speed up when ompared to simple non-vectorized operations.


2) what is broadcasting in python:

the term broadcastin refers to the ability of numpy to treat arrays with different dimensions during arithmetic   operations.
this processes involves certain rules that allow the smaller array to be broadcast  across the larger one ensuring that they hace compatible shapes for these operations








PRACTICLE QUESTION

Q1. create a 3*3 numpy array with random integers between 1 and 100. then , interchange its row and columns.

In [1]:
import numpy as np
array = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(array)
interchanged_array = array.transpose()

print("\nArray with rows and columns interchanged:")
print(interchanged_array)


Original array:
[[ 4 60 18]
 [38 87 47]
 [80 58 89]]

Array with rows and columns interchanged:
[[ 4 38 80]
 [60 87 58]
 [18 47 89]]


Q2.generate a 1d numpy array with 10 elements. reshape it into a 2*5 array, then into a 5*2 array.


In [2]:


import numpy as np


arr_1d = np.arange(10)
print("Original 1D array:", arr_1d)


arr_2x5 = arr_1d.reshape(2, 5)
print("\nReshaped into a 2x5 array:\n", arr_2x5)


arr_5x2 = arr_1d.reshape(5, 2)
print("\nReshaped into a 5x2 array:\n", arr_5x2)


Original 1D array: [0 1 2 3 4 5 6 7 8 9]

Reshaped into a 2x5 array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into a 5x2 array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Q3.create a 4*4 numpy array with random float values. add a border of zeros around it, resulting in a 6 * 6  array.


In [3]:
import numpy as np
array = np.random.rand(4, 4)
padded_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("Original array:\n", array)
print("\nPadded array:\n", padded_array)


Original array:
 [[0.64293792 0.29384186 0.99199991 0.27822609]
 [0.26836482 0.25087116 0.26733118 0.8249517 ]
 [0.09112166 0.61901242 0.24021812 0.35151283]
 [0.19221679 0.34300595 0.75033853 0.19753544]]

Padded array:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.64293792 0.29384186 0.99199991 0.27822609 0.        ]
 [0.         0.26836482 0.25087116 0.26733118 0.8249517  0.        ]
 [0.         0.09112166 0.61901242 0.24021812 0.35151283 0.        ]
 [0.         0.19221679 0.34300595 0.75033853 0.19753544 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q4. using numpy, create an array of integers from 10 to 60 with a step of 5

In [4]:


import numpy as np

array = np.arange(10, 61, 5)
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


Q5.create a numpy  array of ssrings ["python,"numpy","pandas"] apply different case transformations (uppercase,lowercasse,little case) to each elemnet.


In [5]:
import numpy as np
strings = np.array(["python", "numpy", "pandas"])
uppercase_strings = [s.upper() for s in strings]
lowercase_strings = [s.lower() for s in strings]
titlecase_strings = [s.title() for s in strings]
print("Original strings:", strings)
print("Uppercase strings:", uppercase_strings)
print("Lowercase strings:", lowercase_strings)
print("Titlecase strings:", titlecase_strings)


Original strings: ['python' 'numpy' 'pandas']
Uppercase strings: ['PYTHON', 'NUMPY', 'PANDAS']
Lowercase strings: ['python', 'numpy', 'pandas']
Titlecase strings: ['Python', 'Numpy', 'Pandas']


Q6. generate a numpy array of words. insert a space between each character of every word in the array.


In [6]:
import numpy as np
words = np.array(['hello', 'world', 'numpy'])
spaced_words = [' '.join(list(word)) for word in words]
print(spaced_words)


['h e l l o', 'w o r l d', 'n u m p y']


Q7.create two 2d numpy arrays and perdorm elements-wise addition,substraction,multiplication, and division.

In [ ]:
import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
addition_result = array1 + array2
print("Element-wise addition:\n", addition_result)
subtraction_result = array1 - array2
print("\nElement-wise subtraction:\n", subtraction_result)
multiplication_result = array1 * array2
print("\nElement-wise multiplication:\n", multiplication_result)
division_result = array1 / array2
print("\nElement-wise division:\n", division_result)


Q8.use numpy to create a 5 * 5 identity matrix, then extract its diagonal element .

In [ ]:
import numpy as np
identity_matrix = np.identity(5)
print("5x5 Identity Matrix:\n", identity_matrix)
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


Q9.generate a numpy array of 100 random integers between 0 and 1000 . find and display all prime numbers in this array.


In [ ]:
# prompt: generate a numpy aarray of 100 random integers between 0 and 1000 find and display all prime numbers in this array.

import numpy as np

def is_prime(n):
  """Checks if a number is prime."""
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]
print("Prime numbers in the array:", prime_numbers)


In [8]:
import numpy as np
def is_prime(n):
  """Checks if a number is prime."""
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True
random_integers = np.random.randint(0, 1001, size=100)
prime_numbers = [num for num in random_integers if is_prime(num)]
print("Prime numbers in the array:", prime_numbers)

Prime numbers in the array: [29, 337, 827, 653, 613, 439, 641, 401, 167, 431, 101]


Q10. create a numpy array representing daily temperatures for a month. calculate and display the weekly average.

In [9]:
import numpy as np
daily_temperatures = np.random.randint(15, 35, size=30)
weekly_averages = []
for i in range(0, len(daily_temperatures), 7):
    week_temperatures = daily_temperatures[i:i + 7]
    weekly_average = np.mean(week_temperatures)
    weekly_averages.append(weekly_average)
print("Daily Temperatures:", daily_temperatures)
print("Weekly Average Temperatures:", weekly_averages)


Daily Temperatures: [16 31 21 30 33 32 17 28 26 28 31 19 30 34 27 19 26 19 28 20 19 24 25 25
 23 17 17 29 32 20]
Weekly Average Temperatures: [25.714285714285715, 28.0, 22.571428571428573, 22.857142857142858, 26.0]
